# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
config.vm.hostname = "nginx"

config.vm.network "public_network", bridge: "eth1", auto_config: true
#Host-only

config.vm.provider "virtualbox" do |vb|
vb.name = "nginx"
vb.memory = "1024"
vb.cpus = 2
end

config.vm.synced_folder "./www", "/var/www/html"
config.vm.synced_folder "./sites-available", "/etc/nginx/sites-available/"
config.vm.provision "shell", inline: "cp /vagrant/01apt-cacher-ng /etc/apt/apt.conf.d/"
config.vm.provision "shell", path: "nginx.sh"
config.vm.provision "shell", path: "deleteroute.sh", run: "always"

config.vm.post_up_message = "Para acceder executa vagrant ssh"
end