# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
config.vm.hostname = "web"

config.vm.network "private_network", ip: "192.168.56.100"

config.vm.provider "virtualbox" do |vb|
vb.name = "web"
vb.memory = "1024"
vb.cpus = 2
end

config.vm.synced_folder "./www", "/var/www/html"
config.vm.provision "shell", inline: "cp /vagrant/01apt-cacher-ng /etc/apt/apt.conf.d/"
config.vm.provision "shell", path: "apache2.sh"
config.vm.provision "shell", path: "deleteroute.sh", run: "always"

config.vm.post_up_message = "Para acceder executa vagrant ssh"
end