######## TABLE NAT
iptables -t nat -F 

iptables -t nat -P PREROUTING ACCEPT 
iptables -t nat -P INPUT ACCEPT 
iptables -t nat -P OUTPUT ACCEPT 
iptables -t nat -P POSTROUTING ACCEPT 
iptables -t nat -A POSTROUTING -s 172.16.1.0/24 -j SNAT --to-source 192.168.1.157

# Completed on Mon Nov 29 11:01:02 2021
# Generated by iptables-save v1.6.2 on Mon Nov 29 11:01:02 2021
####### TABLE FILTER

########################### CHAIN INPUT #########################
iptables -F
# Para que non se caiga cando facemos o Vagrant up e necesario deixar esta regra.
iptables -A INPUT -p tcp --dport 22 -i eth0 -j ACCEPT
# Connection Tracking
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Loopback
iptables -A INPUT -i lo -m conntrack --ctstate NEW -j ACCEPT

# Ping dende a rede interna
iptables -A INPUT -p icmp --icmp-type 8 -s 172.16.1.0/24 -i eth2 -m conntrack --ctstate NEW -j ACCEPT

# SSH dende Vagrant ssh
iptables -A INPUT -p tcp --dport 22 -i eth0 -m conntrack --ctstate NEW -j ACCEPT

# SSH dende o anfitrion
iptables -A INPUT -p tcp --dport 22 -s 192.168.1.31 -i eth1 -m conntrack --ctstate NEW -j ACCEPT

# SSH dende TRONO-01
iptables -A INPUT -p tcp --dport 22 -s 172.16.1.2 -i eth2 -m conntrack --ctstate NEW -j ACCEPT
# NO LOGGING
iptables -A INPUT -d 10.0.2.255/32 -j DROP
iptables -A INPUT -d 192.168.255.255/32 -j DROP
iptables -A INPUT -d 172.16.1.255/32 -j DROP
iptables -A INPUT -d 255.255.255.255/32 -j DROP
iptables -A INPUT -d 224.0.0.1/32 -j DROP
# Loguear o que se vai dropear
iptables -A INPUT -m conntrack --ctstate NEW -j LOG --log-prefix "iptables: DROP INPUT: "
########################### CHAIN OUTPUT ########################

# Para que non se caiga cando facemos o Vagrant up e necesario deixar esta regra.
iptables -A OUTPUT -p tcp --sport 22 -o eth0 -j ACCEPT


# Connection Tracking
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Loopback
iptables -I OUTPUT 2 -o lo -m conntrack --ctstate NEW -j ACCEPT

# Ping a outras redes
iptables -A OUTPUT  -p icmp --icmp-type 8  -m conntrack --ctstate NEW -j ACCEPT

# DNS
iptables -A OUTPUT -p udp --dport 53  -m conntrack --ctstate NEW -j ACCEPT

# NTP
iptables -A OUTPUT -p udp --dport 123 -m conntrack --ctstate NEW -j ACCEPT



# Trafico web
iptables -A OUTPUT -p tcp --dport 80  -m conntrack --ctstate NEW -j ACCEPT

# LOGUEAR o que se vai a tirar
iptables -A OUTPUT -m conntrack --ctstate NEW -j LOG --log-prefix "iptables: DROP OUTPUT: "
########################### CHAIN FORWARD #######################
# Connection Tracking
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# ping 
iptables -A FORWARD -p icmp --icmp-type 8 -s 172.16.1.0/24 -m conntrack --ctstate NEW -j ACCEPT

# DNS
iptables -A FORWARD -p udp --dport 53 -d 192.168.10.10 -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -p udp --dport 53 -d 8.8.8.8 -m conntrack --ctstate NEW -j ACCEPT
# NTP
iptables -A FORWARD -p udp --dport 123 -m conntrack --ctstate NEW -j ACCEPT


# WEB
iptables -A FORWARD -p tcp --dport 80 -m conntrack --ctstate NEW -j LOG --log-prefix "iptables WEB FORWARD: "
iptables -A FORWARD -p tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT 
iptables -A FORWARD -p tcp --dport 443 -m conntrack --ctstate NEW -j LOG --log-prefix "iptables WEB FORWARD: "
iptables -A FORWARD -p tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT 

# LOGUEAR o que se vai tirar

iptables -A FORWARD  -m conntrack --ctstate NEW -j LOG --log-prefix "iptables DROP FORWARD: "

iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
