# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder "./config", "/etc/squid"
  config.vm.provision "shell", inline: "apt update && apt install squid -y"
end
