# -*- mode: ruby -*-
# vi: set ft=ruby :
lan1 = [

    { nome: "ServidorWeb", id: 1 , software:"apache2"},

    { nome: "DNS", id: 2, software:"bind9" },

]
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory="2048"
      vb.cpus= 2
      vb.linked_clone = true
	  vb.customize ["modifyvm", :id, "--groups", "/Router-UFW"]
    end

  config.vm.box_check_update = false
  # R-INT
  config.vm.define "ROUTER" do |router|	
  	router.vm.box = "debian/bullseye64"
	router.vm.hostname = "R-INT"
	

	router.vm.network "private_network", ip: "172.16.1.1", netmask: "255.255.255.0", virtualbox__intnet: "UFW-LAN-1"
	
	router.vm.provider "virtualbox" do |vb|
		vb.name="Router"
	end
	
	
	router.vm.provision "shell", inline: "cp /vagrant/01apt-cacher-ng /etc/apt/apt.conf.d/"
	router.vm.provision "shell", name: "converte a máquina nun router", path: "router-ufw.bash"
  end

  lan1.each do |lan1|

	config.vm.define "#{lan1[:nome]}" do |node|
		node.vm.box = "debian/bullseye64"
		node.vm.hostname = "#{lan1[:nome]}"

		node.vm.network "private_network", ip: "172.16.1.2#{lan1[:id]}", netmask: "255.255.255.0", virtualbox__intnet: "UFW-LAN-1"
		node.vm.provider "virtualbox" do |vb|
			vb.name="#{lan1[:nome]}"
		end
	   node.vm.provision "shell", path: "cambia-default-route-LAN.sh", run: "always"
	   node.vm.provision "shell", inline:"apt update && apt install #{lan1[:software]} -y"
	end
end
end