# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory="2048"
      vb.cpus= 2
      vb.linked_clone = true
	  vb.customize ["modifyvm", :id, "--groups", "/Router-UFW"]
    end

  config.vm.box_check_update = false
  # R-INT
  config.vm.define "ROUTER" do |router|	
  	router.vm.box = "debian/bullseye64"
	router.vm.hostname = "R-INT"
	
	router.vm.network "public_network", bridge: "eth1", auto_config: true
	router.vm.network "private_network", ip: "172.16.1.1", netmask: "255.255.255.0", virtualbox__intnet: "UFW-LAN-1"
	
	router.vm.provider "virtualbox" do |vb|
		vb.name="Router"
	end
	
	router.vm.provision "shell", inline: "cp /vagrant/01apt-cacher-ng /etc/apt/apt.conf.d/"
	router.vm.provision "shell", name: "cambia a porta de enlace", path: "cambia-default-route.sh", run: "always"
	router.vm.provision "shell", name: "converte a máquina nun router", path: "ufw.sh"
	router.vm.provision "shell",name: "instalando DNS", path: "instalacion-dns.sh"
	router.vm.provision "shell",name: "instalando DHCP", path: "instalacion-dhcp.sh"
	router.vm.provision "shell", inline: "systemctl status isc-dhcp-server", run: "always"
	#hay que reiniciar la maquina para que arranque el dhcp.

  end
  config.vm.define "web" do |web|
	web.vm.box = "debian/bullseye64"
	web.vm.hostname = "web"

	web.vm.network "private_network", ip: "172.16.1.10", netmask: "255.255.255.0", virtualbox__intnet: "UFW-LAN-1"

	web.vm.provision "shell", inline: "echo Procesando maquina"
	web.vm.provision "shell", inline: "echo Monstrando a configuracion ip: && ip a"
	web.vm.provision "shell", inline: "cat /vagrant/resolv > /etc/resolv.conf", run: "always"
	
	web.vm.provision "shell", inline: "echo install; apt update; apt install apache2 -y"
	web.vm.provision "shell",name: "cambia a porta de enlace", path: "cambia-default-route-LAN.sh", run: "always"

	web.vm.provider "virtualbox" do |vb|
	  vb.name = "web"
	  vb.memory = "1024"
	  vb.cpus = 1
	  vb.linked_clone = true
  end
end
  config.vm.define "ubuntu" do |ubuntu|
	ubuntu.vm.box = "ubuntu/focal64"
	ubuntu.vm.hostname = "ubuntu"

	
	ubuntu.vm.network "private_network", type: "dhcp" , virtualbox__intnet: "UFW-LAN-1"

	ubuntu.vm.provision "shell", inline: "echo Procesando maquina"
	ubuntu.vm.provision "shell", inline: "echo Monstrando a configuracion ip: && ip a"
	ubuntu.vm.provision "shell", inline: "cat /vagrant/resolv > /etc/resolv.conf", run: "always"
	ubuntu.vm.provision "shell",name: "cambia a porta de enlace", path: "cambia-default-route-ubuntu.sh", run: "always"

	ubuntu.vm.provider "virtualbox" do |vb|
	  vb.name = "ubuntu"
	  vb.memory = "1024"
	  vb.cpus = 1
	  vb.linked_clone = true
  end
end
config.vm.define "ubuntu2" do |ubuntu2|
	ubuntu2.vm.box = "ubuntu/focal64"
	ubuntu2.vm.hostname = "ubuntu2"

	#ubuntu2.vm.network "private_network", ip: "172.16.2.100", netmask: "255.255.255.0", virtualbox__intnet: "UFW-LAN-2"
	ubuntu2.vm.network "private_network", type: "dhcp" , virtualbox__intnet: "UFW-LAN-2"

	ubuntu2.vm.provision "shell", inline: "echo Procesando maquina"
	ubuntu2.vm.provision "shell", inline: "echo Monstrando a configuracion ip: && ip a"
	ubuntu2.vm.provision "shell", inline: "cat /vagrant/resolv2 > /etc/resolv.conf", run: "always"
	ubuntu2.vm.provision "shell",name: "cambia a porta de enlace", path: "cambia-default-route-ubuntu2.sh", run: "always"

	ubuntu2.vm.provider "virtualbox" do |vb|
	  vb.name = "ubuntu2"
	  vb.memory = "1024"
	  vb.cpus = 1
	  vb.linked_clone = true
  end
end
end