# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
	vb.memory="2048"
	vb.cpus= 2
	vb.linked_clone = true
	vb.customize ["modifyvm", :id, "--groups", "/E-Apt-Cacher"]
  end

  config.vm.box_check_update = false
  # R-INT
  config.vm.define "ROUTER" do |router|	
  	router.vm.box = "debian/bookworm64"
	router.vm.hostname = "R-INT"
	

	router.vm.network "public_network", bridge: "enp2s0", auto_config: false 
	router.vm.network "private_network", ip: "172.16.1.1", netmask: "255.255.255.0", virtualbox__intnet: "E-APT-CACHER-LAN"
	
	router.vm.provider "virtualbox" do |vb|
		vb.name="Router"
		vb.memory = "756"
	end
	
	
	router.vm.provision "shell", name: "configura o interface bridge", path: "configura-bridge.sh", run: "always"
	router.vm.provision "shell", name: "cambia a porta de enlace", path: "cambia-default-route.sh", run: "always"
	router.vm.provision "shell", name: "converte a máquina nun router", inline: "sysctl -w net.ipv4.ip_forward=1", run: "always"
	
	
	#### NFTABLES
	router.vm.provision "shell", name: "copia e carga as regras nftables", inline: "cp /vagrant/nftables.conf /etc && /etc/nftables.conf", run: "always"
  end
  # APT-cacher
  config.vm.define "APT-Cacher" do |aptcacher|	
	aptcacher.vm.box = "debian/bookworm64"
	aptcacher.vm.hostname = "APT-Cacher"
  

	aptcacher.vm.network "private_network", ip: "172.16.1.2", netmask: "255.255.255.0", virtualbox__intnet: "E-APT-CACHER-LAN"
  
	aptcacher.vm.provider "virtualbox" do |vb|
	  vb.name="apt-cacher"
	  vb.memory = "756"
  end
  
  aptcacher.vm.provision "shell", path: "cambia-default-route-LAN.sh", run: "always"
  aptcacher.vm.provision "shell", inline: "cp /vagrant/01apt-cacher-ng /etc/apt/apt.conf.d/"
  aptcacher.vm.provision "shell", path: "instalacion-cacher.sh"
  
  
	end

end